services:
  cashcue_db:
    image: mariadb:11
    container_name: cashcue_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u root -p$${MYSQL_ROOT_PASSWORD} --protocol=tcp -e 'SELECT 1;' >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  cashcue_app:
    environment:
      DB_HOST: cashcue_db
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: cashcue_app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      # Full project tree
      - ../:/data/cashcue

      # Config file
      - ../conf/cashcue.conf:/etc/cashcue/cashcue.conf:ro
    depends_on:
      cashcue_db:
        condition: service_healthy

volumes:
  db_data: